################################################################################
# Input configuration                                                          #
################################################################################

input:
  # Optional: input directory to use for fastq files (for local input files).
  dir: input


################################################################################
# Pipeline options                                                             #
################################################################################

options:
  pdx: true
  readgroup:
    platform: ILLUMINA
    centre: CENTRE


################################################################################
# References                                                                   #
################################################################################

references:
  genome: input/reference.fa
  bwa_index: "/path/to/index"
  bwa_index_host: "/path/to/index_host"
  capture: input/capture.bed
  capture_intervals: input/capture.intervals


################################################################################
# Rule configuration                                                           #
################################################################################

rules:
  cutadapt:
    extra:
    - "-a AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC"
    - "-A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT"
    - "-q 20"
    - "--minimum-length 60"
    threads: 5
  bwa:
    extra:
    - "-M"
    sort_extra: []
    threads: 10
  samtools_merge:
    extra: []
    threads: 10
  picard_mark_duplicates:
    extra:
    - "-XX:ParallelGCThreads=5"
    - VALIDATION_STRINGENCY=LENIENT
  picard_collect_hs_metrics:
    extra: "-Xmx4g"
  multiqc:
    extra: []
  fastqc:
    extra: []
  disambiguate:
    extra: []
  sambamba_sort:
    extra: []
    threads: 5


################################################################################
# Sample configuration                                                         #
################################################################################

samples:
  S1:
  - S1.L001
  - S1.L002
units:
  S1.L001:
  - S1.L001.R1.fastq.gz
  - S1.L001.R2.fastq.gz
  S1.L002:
  - S1.L002.R1.fastq.gz
  - S1.L002.R2.fastq.gz